# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Code Viz Cafe"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: shreyas.rh9@gmail.com
#blog logo
logo: "/assets/images/rh_logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/welcome.jpg"

name: 'Shreyas R H'
author: 'Shreyas R H'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@rh_shreyas'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/rh_shreyas
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/shreyasrh9
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

theme: jekyll-theme-tactile